# .gitlab-ci.yml

sync_from_github_debug_v2:
  stage: deploy
  image: alpine/git:latest

  tags:
    - docker

  script:
    # The '|' tells YAML to treat the following indented block as a single string.
    # 'set -ex' prints each command before running it (for debugging) and exits on any error.
    - |
      set -ex

      echo "--- Starting sync from GitHub (DEBUG) ---"

      # We are using the hardcoded URL to ensure there are no variable expansion issues.
      git clone --mirror "https://github.com/justncodes/Kingshot-Discord-Bot-Dev.git" .

      echo "--- Clone command completed. Setting remote for GitLab... ---"
      git remote set-url --push origin "https://${CI_REGISTRY_USER}:${CI_JOB_TOKEN}@${CI_PROJECT_URL#https://}.git"

      echo "--- Pushing mirror to GitLab at ${CI_PROJECT_URL} ---"
      git push --mirror origin

      echo "--- Sync complete. ---"

  rules:
    # Run ONLY when triggered by a webhook.
    - if: '$CI_PIPELINE_SOURCE == "trigger"'