# .gitlab-ci.yml

variables:
  GITHUB_REPO_URL: "https://github.com/justncodes/Kingshot-Discord-Bot-Dev.git"

sync_from_github:
  stage: deploy
  image:
    name: alpine/git:latest    
    entrypoint: [""] # Tells the runner to start a standard shell, which can then hopefully execute our script.

  tags:
    - docker

  script:
    - echo "Starting sync from GitHub..."
    - set -x # Keep for debugging

    # Clone the source repository from GitHub as a mirror.
    - git clone --mirror $GITHUB_REPO_URL .

    # Set the push URL to the current GitLab project.
    - echo "Clone complete. Setting remote..."
    - git remote set-url --push origin "https://${CI_REGISTRY_USER}:${CI_JOB_TOKEN}@${CI_PROJECT_URL#https://}.git"

    # Push the mirror to the GitLab repository.
    - echo "Pushing mirror to GitLab at ${CI_PROJECT_URL}..."
    - git push --mirror origin

    - echo "Sync complete."

  rules:
    # Run ONLY when triggered by a webhook.
    - if: '$CI_PIPELINE_SOURCE == "trigger"'