# .gitlab-ci.yml

variables:
  GITHUB_REPO_URL: "https://github.com/justncodes/Kingshot-Discord-Bot-Dev.git"

sync_from_github:
  stage: deploy
  image:
    name: alpine/git:latest
    entrypoint: [""]
  tags:
    - docker

  script:
    - echo "Adding GitHub as a remote..."
    - git remote add github $GITHUB_REPO_URL
    - echo "Fetching all data from GitHub..."
    - git fetch --prune github
    - echo "Pushing mirror to GitLab using Project Access Token..."
    - git push --prune "https://gitlab-ci:${GITLAB_PUSH_TOKEN}@${CI_PROJECT_URL#https://}" 'refs/remotes/github/*:refs/heads/*' --tags
    - echo "Sync complete."

  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'